### ISSUE TITLE
CIFAR-10-C-Bar dataset?

### ISSUE THREAD

**Issue by khawar-islam** [hzlsaber/IPMix#1]
Hello @hzlsaber 

What is `CIFAR-10-C-Bar` in your `cifar.py `file

**Comment by hzlsaber** [comment]
Hi, thank you for reaching out with your question.

To address your concern, you'll find the necessary information in the cifar.py file, specifically from lines 368 to 383. Here's a brief guide on how to configure the data paths for training with the CIFAR datasets:

CIFAR-100 Dataset Path: According to line 378 in the script, the path specified by **args.data_path + 'cifar'** should lead to your CIFAR-100 dataset (typically named cifar-100-python).

CIFAR-100-C dataset Path: As per line 381, the path indicated by **args.data_path + 'cifar/CIFAR-100-C'** should be the directory where your CIFAR-100-C dataset is located.

Here is an example. I use **"--data_path /home/ccf_disk/cifar_dataset/cifar"** to train IPMix with CIFAR-100.

![1702606264806](https://github.com/hzlsaber/IPMix/assets/147322689/2a7e25ad-948d-45af-863d-c1b13ee945a9)

**Comment by hzlsaber** [comment]
You can use “base_c_bar_path” to test IPMix with CIFAR-C-bar, just like CIFAR-C. 
 You need to remove the comments on lines 528, 529, and 531. This will activate the code that enables testing with the CIFAR-10-C-Bar dataset.
Please download CIFAR-C-bar dataset and make sure the path is correct.

**Comment by khawar-islam** [comment]
@hzlsaber thank you for your answer I have cifar100 and cifar100-C but CIFAR-C-Bar is missing. If you can give me the link of CIFAR-C-Bar then i will also download it please

**Comment by hzlsaber** [comment]
You can find some useful information from here: https://github.com/facebookresearch/augmentation-corruption
I think it may take some time for you to generate CIFAR-C-Bar.
Good luck!

**Comment by khawar-islam** [comment]
@hzlsaber thank you very much
