### ISSUE TITLE
Visual comparison of various data augmentation methods. [PixMix, IPMix]

### ISSUE THREAD

**Issue by khawar-islam** [hzlsaber/IPMix#6]
Hello @hzlsaber 

Happy new year. I would like to cite your paper in my upcoming paper and I just need visual code of PixMix and IPMix. I want to generate images only for comparison like figure 1 as my all images are related to bird that's why i need to construct it  again. Do you have a code only?

Regards,
Khawar

**Comment by hzlsaber** [comment]
Hello,

Happy New Year! I wanted to clarify that figure 1 were created using photo editing software, not generated by code. Which is a common practice used in CutMix, PixMix, and AugMix to best illustrate the methods' features.

I suggest using software like Photoshop to create your own visuals for comparison. It offers flexibility to highlight your research's key points. If you need guidance or have questions, feel free to ask.

Best wishes on your paper!

**Comment by khawar-islam** [comment]
@hzlsaber thanks sure i will do it, if you have Photoshop file you can share with me, i will change the picture and put it into the paper.  In that way, i will represent your method more correctly.

**Comment by khawar-islam** [comment]
Dear @hzlsaber 

I want to include your paper in my paper and also diagram, I tried to make a diagram on photo editing tools which not looks good. If you apply IPMix on below image, it would be very helpful I will include this image in my paper as well to demonstrate the idea of IPMix .

![bird2](https://github.com/hzlsaber/IPMix/assets/11488932/98a39a54-24cf-4044-bb46-57719bd39e80)

**Comment by khawar-islam** [comment]
Dear @hzlsaber If you have please let me know, I have to add and cite your paper in my paper.

**Comment by hzlsaber** [comment]
Hi,

Thank you for your reaching out. I'm sorry for the late since I am busy with my papers.

I think you can use this photo for visualization.

Best,  
![099e2875df333c7c5c6c7bab6429f18](https://github.com/hzlsaber/IPMix/assets/147322689/acb444b7-2617-4892-af6b-aa190884318e)

**Comment by khawar-islam** [comment]
@hzlsaber thank you very much
